import { Header } from "@/components/Header";
import type { Metadata } from "next";
import {
    IBM_Plex_Mono,
    Nunito_Sans,
} from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito_Sans({
    subsets: ["latin"],
    variable: "--font-family-sans",
});

const ibmPlexMono = IBM_Plex_Mono({
    subsets: ["latin"],
    variable: "--font-family-code",
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${nunitoSans.variable} ${ibmPlexMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Header />
                {children}
            </body>
        </html>
    );
}
